import { Typography } from '@mui/material';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Challenger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <div>Challenger!</div>
        <Typography variant="h3" color="primary.main">
          test
        </Typography>
      </div>
    </>
  );
}
